/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				'surface': '#fcf9f2',
				'surface-dim': '#dcdad3',
				'surface-bright': '#fcf9f2',
				'surface-container-lowest': '#ffffff',
				'surface-container-low': '#f6f3ec',
				'surface-container': '#f1eee7',
				'surface-container-high': '#ebe8e1',
				'surface-container-highest': '#e5e2db',
				'on-surface': '#1c1c18',
				'on-surface-variant': '#56423d',
				'inverse-surface': '#31312c',
				'inverse-on-surface': '#f3f0e9',
				'outline': '#89726c',
				'outline-variant': '#ddc0b9',
				'surface-tint': '#9e4127',
				'primary': '#9b3f25',
				'on-primary': '#ffffff',
				'primary-container': '#bb563b',
				'on-primary-container': '#fffbff',
				'inverse-primary': '#ffb5a1',
				'secondary': '#7b5455',
				'on-secondary': '#ffffff',
				'secondary-container': '#fdcbcb',
				'on-secondary-container': '#795354',
				'tertiary': '#5a5f42',
				'on-tertiary': '#ffffff',
				'tertiary-container': '#727759',
				'on-tertiary-container': '#fcffe1',
				'error': '#ba1a1a',
				'on-error': '#ffffff',
				'error-container': '#ffdad6',
				'on-error-container': '#93000a',
				'primary-fixed': '#ffdbd1',
				'primary-fixed-dim': '#ffb5a1',
				'on-primary-fixed': '#3b0800',
				'on-primary-fixed-variant': '#7f2a12',
				'secondary-fixed': '#ffdad9',
				'secondary-fixed-dim': '#ecbbba',
				'on-secondary-fixed': '#2f1314',
				'on-secondary-fixed-variant': '#603d3e',
				'tertiary-fixed': '#e1e6c1',
				'tertiary-fixed-dim': '#c5caa6',
				'on-tertiary-fixed': '#191d07',
				'on-tertiary-fixed-variant': '#44492e',
				'background': '#fcf9f2',
				'on-background': '#1c1c18',
				'surface-variant': '#e5e2db',
			},
			borderRadius: {
				'sm': '0.125rem',
				'DEFAULT': '0.25rem',
				'md': '0.375rem',
				'lg': '0.5rem',
				'xl': '0.75rem',
				'full': '9999px',
			},
			spacing: {
				'container-max': '1140px',
				'gutter': '24px',
				'margin-mobile': '20px',
				'margin-desktop': '64px',
				'unit': '8px',
				'stack-sm': '12px',
				'stack-md': '24px',
				'stack-lg': '48px',
				'section-gap-mobile': '64px',
				'section-gap-desktop': '120px',
			},
			fontFamily: {
				'display-lg': ['Playfair Display', 'serif'],
				'display-lg-mobile': ['Playfair Display', 'serif'],
				'headline-md': ['Playfair Display', 'serif'],
				'headline-sm': ['Playfair Display', 'serif'],
				'body-lg': ['Source Sans 3', 'sans-serif'],
				'body-md': ['Source Sans 3', 'sans-serif'],
				'label-caps': ['Source Sans 3', 'sans-serif'],
			},
			fontSize: {
				'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
				'display-lg-mobile': ['36px', { lineHeight: '42px', fontWeight: '700' }],
				'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
				'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
				'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
				'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
				'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
			},
		},
	},
	plugins: [],
}
